### ISSUE TITLE
How can I how to load formulas from a database or configuration file

### ISSUE THREAD

**Issue by oneyh** [Ismail-Mekni/mxreflection#1]
The design of this library is exciting, but I want to know how to load formulas from a database or configuration file。

**Comment by Ismail-Mekni** [comment]
Hello Oneyh,
Thank you for your comment. Dynamically loading formulas at runtime is not supported yet by mxreflection. I'm going to start working on that feature, it will be available by the end of the year.

**Comment by Ismail-Mekni** [comment]
> The design of this library is exciting, but I want to know how to load formulas from a database or configuration file。

Hello Oneyh,
Thank you for your comment. Dynamically loading formulas at runtime is not supported yet by mxreflection. I'm going to start working on that feature, it will be available by the end of the year.

**Comment by oneyh** [comment]
> > The design of this library is exciting, but I want to know how to load formulas from a database or configuration file。
> 
> Hello Oneyh, Thank you for your comment. Dynamically loading formulas at runtime is not supported yet by mxreflection. I'm going to start working on that feature, it will be available by the end of the year.

I am so happy to get that and looked forward to it
