### ISSUE TITLE
sum the same property value for multiple objects

### ISSUE THREAD

**Issue by oneyh** [Ismail-Mekni/mxreflection#2]
Can I sum the same property value for multiple objects? If I could, how should I write the max expression.

**Comment by Ismail-Mekni** [comment]
> Can I sum the same property value for multiple objects? If I could, how should I write the max expression.

Hello Oneyh,
 Could you give an example about what you are trying to do? I couldn't understand what do you mean exactly.

**Comment by oneyh** [comment]
// Just like this

class Subject {

    String subjectName;
    @Arg("sc")
    String subjectScore;

    @Arg("tSc")
    @Expression("How to write the formula here?")
    String totalScore;

    public static void main(String[] args) {
        Subject s1 = new Subject();
        s1.subjectName = "math";
        s1.subjectScore = "80";
        Subject s2 = new Subject();
        s2.subjectName = "physics";
        s2.subjectScore = "70";
        Subject s3 = new Subject();
        s3.subjectName = "chemistry";
        s3.subjectScore = "90";

        // I want to assign the total score to the totalScore attributes of each object
    }
}

**Comment by Ismail-Mekni** [comment]
> // Just like this
> 
> class Subject {
> 
>     String subjectName;
>     @Arg("sc")
>     String subjectScore;
> 
>     @Arg("tSc")
>     @Expression("How to write the formula here?")
>     String totalScore;
> 
>     public static void main(String[] args) {
>         Subject s1 = new Subject();
>         s1.subjectName = "math";
>         s1.subjectScore = "80";
>         Subject s2 = new Subject();
>         s2.subjectName = "physics";
>         s2.subjectScore = "70";
>         Subject s3 = new Subject();
>         s3.subjectName = "chemistry";
>         s3.subjectScore = "90";
> 
>         // I want to assign the total score to the totalScore attributes of each object
>     }
> }

Now I understand, thank you.
There is no way you can do it only with MxReflection. For now, I don't preview to add this feature to the library, Sorry.
